name: Let's build a Helm Secret

on:
  workflow_dispatch:
  
env:
  HS_REPO: https://github.com/jkroepke/helm-secrets.git
  WORKDIR: hs
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

    - name: Check it out
      run: git clone ${{ env.HS_REPO }} ${{ env.WORKDIR }}

    - name: Docker-build it
      working-directory: ${{ env.WORKDIR }}
      run: |
        echo ${{ secrets.DOCKERHUB }} | docker login -u qrkot --password-stdin
        docker build -t qrkot/helmsec-bundle:latest .
        docker logout
