name: Let's build a Helm Secret

on:
  workflow_dispatch:
  
env:
  HS_REPO: https://github.com/jkroepke/helm-secrets.git
  WORKDIR: helmsec
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

    - name: Checkout it out
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Check out Helm Secrets
      run: git clone ${{ env.HS_REPO }} ${{ env.WORKDIR }}

    - name: Docker-build it
      run: |
        docker build .
#        echo ${{ secrets.DOCKERHUB }} | docker login -u ${{ secrets.DOCKERHUB_USER }} --password-stdin
#        docker build -t qrkot/helmsec-bundle:latest .
#        docker push ${{ secrets.DOCKERHUB_USER }}/helmsec-bundle
#       docker logout
